Host: http://localhost:8080

POST /users
{"name":"Jason", "password":"1234"}

GET /login

TEMPLATE cookies
${set_cookies()}

POST /login | cookies
{"name":"Shannon", "password":"password1"} 

GET /users
